version: '3.8'
services:
# -------------------------------------------
  # list of the all containers
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    # expose:
      # - '5000'
    volumes:
      - static_volume:/home/app/backend/static
    env_file:
      - ./.env.prod
    # links:
      # - db
    depends_on:
      - db
# -------------------------------------------
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    #   - db
    ports:
      - "3000:80"
    environment:
      # for windows to update after save
      - CHOKIDAR_USEPOOLING=true
    env_file:
      - ./.env.prod
    links:
      - backend

# -------------------------------------------
  db:
    image: postgres:13-alpine
    volumes:
      - pg_db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
# ------------------------------------------- 
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/backend/static
  #     # - ../frontend/build:/usr/share/nginx/html
  #     # - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
  #   # restart: always
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - backend
      # - frontend

volumes:
  pg_db:
  static_volume:
